name: ${project.name}
version: ${project.version}
author: ${author}
description: YTLiveMC is a Plugin that allows youtube streamers to do something like "sub = die" or "like = spawn tnt"
main: club.siwoo.ytlivemc.YTLiveMC
load: POSTWORLD
website: siwoo.club, siwoo.lol

api-version: 1.13

libraries:
  - org.openjdk.nashorn:nashorn-core:15.4

commands: